# Generated by Django 4.0.3 on 2022-05-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('Nom', models.CharField(max_length=100)),
                ('Prénom', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Adresse', models.CharField(max_length=100)),
                ('Gouvernorat', models.CharField(max_length=100)),
                ('Ville', models.CharField(max_length=100)),
                ('CodePostal', models.CharField(max_length=100)),
                ('AdminPhoto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('DeviceId', models.AutoField(primary_key=True, serialize=False)),
                ('Reference', models.CharField()),
                ('DeviceName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=5000)),
                ('DateOfInstall', models.DateField()),
                ('Etat', models.CharField(max_length=100, null=False) ) ,
                ('Location' , models.CharField(max_length=100, null=False)  ),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('Telephone', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('DateOfJoining', models.DateField()),
                ('Email', models.CharField(max_length=100)),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portes',
            fields=[
                ('PorteNum', models.AutoField(primary_key=True, serialize=False)),
                ('Access', models.CharField(max_length=100)),
                ('Employee', models.CharField(max_length=100)),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
    ]
