# Generated by Django 4.0.3 on 2022-05-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='DeviceId',
            new_name='DeviceNum',
        ),
        migrations.AlterField(
            model_name='devices',
            name='Reference',
            field=models.Field(),
        ),
    ]
