# Generated by Django 4.0.3 on 2022-06-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeApp', '0003_rename_description_devices_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='status',
        ),
        migrations.RemoveField(
            model_name='portes',
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='portes',
            name='PhotoFileName',
        ),
    ]
